# Generated by Django 5.2.6 on 2025-09-18 19:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UnansweredQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_message", models.TextField()),
                (
                    "detected_language",
                    models.CharField(
                        choices=[("en", "English"), ("sn", "Shona")],
                        default="en",
                        max_length=2,
                    ),
                ),
                ("session_id", models.CharField(blank=True, max_length=100, null=True)),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("intent", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "bot_response",
                    models.TextField(help_text="The response that was given"),
                ),
                ("is_processed", models.BooleanField(default=False)),
                ("converted_to_faq", models.BooleanField(default=False)),
                ("admin_notes", models.TextField(blank=True)),
                (
                    "frequency_count",
                    models.IntegerField(
                        default=1, help_text="How many times this question was asked"
                    ),
                ),
                ("first_asked", models.DateTimeField(auto_now_add=True)),
                ("last_asked", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-frequency_count", "-last_asked"],
            },
        ),
        migrations.CreateModel(
            name="ChatAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("total_conversations", models.IntegerField(default=0)),
                ("successful_responses", models.IntegerField(default=0)),
                ("fallback_responses", models.IntegerField(default=0)),
                ("positive_feedback", models.IntegerField(default=0)),
                ("negative_feedback", models.IntegerField(default=0)),
                ("english_conversations", models.IntegerField(default=0)),
                ("shona_conversations", models.IntegerField(default=0)),
                ("top_intents", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("date",)},
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(blank=True, max_length=100, null=True)),
                ("user_message", models.TextField()),
                ("bot_response", models.TextField()),
                (
                    "detected_language",
                    models.CharField(
                        choices=[("en", "English"), ("sn", "Shona")],
                        default="en",
                        max_length=2,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "confidence_score",
                    models.FloatField(
                        blank=True, help_text="Rasa confidence score", null=True
                    ),
                ),
                (
                    "intent",
                    models.CharField(
                        blank=True,
                        help_text="Detected intent from Rasa",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "is_fallback",
                    models.BooleanField(
                        default=False, help_text="Was this a fallback response?"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question",
                    models.TextField(help_text="The question in its original form"),
                ),
                ("answer", models.TextField()),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("sn", "Shona")],
                        default="en",
                        max_length=2,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Registration, Academics, Campus Life",
                        max_length=100,
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated keywords for search",
                        max_length=500,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "usage_count",
                    models.IntegerField(
                        default=0, help_text="How many times this FAQ was served"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_from_unanswered",
                    models.ForeignKey(
                        blank=True,
                        help_text="If this FAQ was created from an unanswered question",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="chat.unansweredquestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "ordering": ["-usage_count", "category"],
            },
        ),
        migrations.CreateModel(
            name="UserLanguagePreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[("en", "English"), ("sn", "Shona")],
                        default="en",
                        max_length=2,
                    ),
                ),
                ("auto_detect", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChatFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("thumbs", "Thumbs Up/Down"),
                            ("stars", "Star Rating"),
                            ("helpful", "Helpful/Not Helpful"),
                            ("detailed", "Detailed Feedback"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_helpful", models.BooleanField(blank=True, null=True)),
                (
                    "star_rating",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "feedback_text",
                    models.TextField(
                        blank=True, help_text="Optional detailed feedback"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="chat.conversation",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "unique_together": {("conversation", "feedback_type")},
            },
        ),
    ]
