# Generated by Django 5.2.6 on 2025-09-19 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MentalHealthResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("emergency", "Emergency Contact"),
                            ("counseling", "Counseling Service"),
                            ("hotline", "Crisis Hotline"),
                            ("online", "Online Resource"),
                            ("campus", "Campus Service"),
                            ("external", "External Service"),
                            ("self_help", "Self-Help Resource"),
                            ("app", "Mobile App"),
                            ("book", "Reading Material"),
                            ("video", "Video Resource"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "urgency_level",
                    models.CharField(
                        choices=[
                            ("immediate", "Immediate Crisis"),
                            ("urgent", "Urgent Support"),
                            ("general", "General Support"),
                            ("preventive", "Preventive Care"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Include country code if international",
                        max_length=50,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website_url", models.URLField(blank=True)),
                ("address", models.TextField(blank=True)),
                ("hours_of_operation", models.CharField(blank=True, max_length=200)),
                ("available_247", models.BooleanField(default=False)),
                (
                    "languages_supported",
                    models.CharField(
                        default="en",
                        help_text="Comma-separated language codes (en, sn, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "location_specific",
                    models.CharField(
                        blank=True,
                        help_text="Specific to country/region (e.g., 'Zimbabwe', 'Harare')",
                        max_length=100,
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=True,
                        help_text="Has this resource been verified as legitimate?",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("usage_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "keywords",
                    models.TextField(
                        blank=True,
                        help_text="Keywords that trigger this resource (comma-separated)",
                    ),
                ),
            ],
            options={
                "ordering": ["urgency_level", "-is_active", "title"],
            },
        ),
        migrations.CreateModel(
            name="MentalHealthInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=100)),
                (
                    "concern_level",
                    models.CharField(
                        choices=[
                            ("crisis", "Crisis - Immediate Intervention"),
                            ("high", "High Concern"),
                            ("moderate", "Moderate Concern"),
                            ("low", "Low Concern"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                ("requires_follow_up", models.BooleanField(default=False)),
                ("follow_up_completed", models.BooleanField(default=False)),
                ("follow_up_notes", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chat.conversation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resources_provided",
                    models.ManyToManyField(blank=True, to="chat.mentalhealthresource"),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="CrisisAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alert_message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New Alert"),
                            ("acknowledged", "Acknowledged"),
                            ("contacted", "User Contacted"),
                            ("resolved", "Resolved"),
                            ("escalated", "Escalated to Professional"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("response_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mental_health_interaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chat.mentalhealthinteraction",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MentalHealthTrigger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trigger_phrase", models.CharField(max_length=200, unique=True)),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("sn", "Shona")],
                        default="en",
                        max_length=2,
                    ),
                ),
                (
                    "concern_level",
                    models.CharField(
                        choices=[
                            ("crisis", "Crisis - Immediate Intervention"),
                            ("high", "High Concern"),
                            ("moderate", "Moderate Concern"),
                            ("low", "Low Concern"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "custom_response",
                    models.TextField(
                        blank=True,
                        help_text="Custom response for this trigger (optional)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "suggested_resources",
                    models.ManyToManyField(blank=True, to="chat.mentalhealthresource"),
                ),
            ],
            options={
                "ordering": ["concern_level", "language", "trigger_phrase"],
            },
        ),
        migrations.AddField(
            model_name="mentalhealthinteraction",
            name="trigger_used",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="chat.mentalhealthtrigger",
            ),
        ),
    ]
