# Generated by Django 5.2.6 on 2025-09-19 13:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_mentalhealthresource_mentalhealthinteraction_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "scheduled_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_sent", models.BooleanField(default=False)),
                (
                    "target_group",
                    models.CharField(
                        choices=[
                            ("all", "All Users"),
                            ("students", "Students"),
                            ("staff", "Staff"),
                        ],
                        default="all",
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
