# Generated by Django 5.2.6 on 2025-09-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="scheduled_time",
            field=models.DateTimeField(),
        ),
    ]
