# Generated by Django 5.2.6 on 2025-09-19 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_notification_is_read"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="is_read",
        ),
    ]
